inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: '2.3'

# This doesn't take into account retrying from an exception
Lint/SuppressedException:
  Enabled: false

# allow String.new to create mutable strings
Style/EmptyLiteral:
  Enabled: false

# allow the use of globals which makes sense in a CLI app like this
Style/GlobalVars:
  Enabled: false
